---

- name: Chef Server Common Tasks
  hosts: all
  sudo: yes
  tags:
    - prod
    - dev

  roles:
    - role: common

  vars_files:
    - settings.yml

- name: Development Environment Tasks
  hosts: vagrant
  sudo: yes
  sudo_user: vagrant
  remote_user: vagrant
  tags: dev

  roles:
    # - role: dev

- name: Production Deploy Tasks
  hosts: production
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  remote_user: "{{ ansible_ssh_user }}"
  tags: prod

  roles:
    # - role: prod
