---
- name: chef reconfigure
  command: chef-server-ctl reconfigure
- name: chef cleanup
  command: chef-server-ctl cleanup
- name: chef upgrade
  command: chef-server-ctl upgrade
- name: chef start
  command: chef-server-ctl start
- name: chef stop
  command: chef-server-ctl stop

- name: create admin
  shell: chef-server-ctl user-create {{ chef.user }} {{ chef.firstname }} {{ chef.lastname }} {{ chef.email }} {{ chef.password }} --filename {{ chef.rsa_file }}

- name: create org
  shell: chef-server-ctl org-create {{ chef.organization_id }} {{ chef.organization }} --association_user {{ chef.user }} {{ chef.password }} -f "/root/{{ chef.organization_id }}-validator.pem"

- name: manage reconfigure
  command: opscode-manage-ctl reconfigure
- name: push jobs reconfigure
  command: opscode-push-jobs-server-ctl reconfigure  
