---
- name: install chef manage
  command: chef-server-ctl install chef-manage
  when: manage.enable
  notify:
  - manage reconfigure
  - chef reconfigure

- meta: flush_handlers

- name: install chef push jobs
  command: chef-server-ctl install opscode-push-jobs-server
  when: pushy.enable
  notify:
  - push jobs reconfigure
  - chef reconfigure

- meta: flush_handlers

- name: install chef reporting
  command: chef-server-ctl install opscode-reporting
  when: reporting.enable
  notify:
  - reporting reconfigure
  - chef reconfigure

- meta: flush_handlers
